name: Arduino AVR Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  get_lib_info:
    runs-on: ubuntu-latest

    outputs:
      lib_dir_name: ${{ steps.get_lib_dir_name.outputs.lib_dir_name }}
      examples: ${{ steps.get_examples.outputs.examples }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: get lib dir name
        id: get_lib_dir_name
        run: |
          LIB_DIR_NAME=$(python script/get_lib_dir_name.py)
          echo "lib_dir_name=${LIB_DIR_NAME}"
          echo "lib_dir_name=${LIB_DIR_NAME}" >> "$GITHUB_OUTPUT"
      - name: get examples
        id: get_examples
        run: |
          EXAMPLES=$(python script/get_examples.py)
          echo "examples=${EXAMPLES}"
          echo "examples=${EXAMPLES}" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: get_lib_info
    env:
      ARDUINO_LIB_DIR_NAME: ${{ needs.get_lib_info.outputs.lib_dir_name }}
    strategy:
      matrix:
        example: ${{ fromJSON(needs.get_lib_info.outputs.examples) }}
        fqbn: ["arduino:avr:uno", "arduino:avr:nano", "arduino:avr:mega"]

    steps:
      - name: download arduino cli
        run: curl -L -o arduino-cli.tar.gz https://github.com/arduino/arduino-cli/releases/download/v1.1.1/arduino-cli_1.1.1_Linux_64bit.tar.gz
      - name: install arduino cli
        run: |
          mkdir -p `pwd`/arduino_cli
          tar -zxvf arduino-cli.tar.gz -C `pwd`/arduino_cli
          export PATH=$PATH:`pwd`/arduino_cli
          alias acli='arduino-cli --config-dir ~/arduino'
      - name: test arduino cli
        run: arduino-cli -v
      - name: setup arduino-cli
        run: |
          acli config init
          acli config set directories.user ~/arduino
          acli config set library.enable_unsafe_install true
          acli config set build_cache.path ~/arduino/build_cache
          acli config dump
          acli core install arduino:avr
      - name: install lib
        run: |
          acli lib install --git-url "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
      - name: compile
        run: |
          echo "compile ~/arduino/libraries/${ARDUINO_LIB_DIR_NAME}/examples/${{matrix.example}}/${{matrix.example}}.ino"
          acli compile --fqbn ${{matrix.fqbn}} "~/arduino/libraries/${ARDUINO_LIB_DIR_NAME}/examples/${{matrix.example}}/${{matrix.example}}.ino" --log --clean -v --verify
