name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: download arduino cli
      run: curl -L -o arduino-cli.tar.gz https://github.com/arduino/arduino-cli/releases/download/v1.1.1/arduino-cli_1.1.1_Linux_64bit.tar.gz
    - name: install arduino cli
      run: tar -zxvf arduino-cli.tar.gz
    - name: test arduino cli
      run: ./arduino-cli -v
    - name: test
      run: |
        echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git""

